name: "pip build and run unit test"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.7", "3.11", "pypy-3.8"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true  

    - name : Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: |
        cd tests
        pytest

